version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip setuptools wheel

  build:
    commands:
      - echo "Building wheel package..."
      - python setup.py bdist_wheel
      - ls -l dist/

artifacts:
  files:
    - dist/*.whl
  discard-paths: yes
